In [5]:
%load_ext autoreload
# %autoreload 2

In [6]:
import logging
from sys import stdout
from datetime import datetime
import numpy as np
import os

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)

logging.info(f"{os.getlogin()}| {datetime.now()}")

[08-17 22:21:19][INFO] DELL| 2025-08-17 22:21:19.359676


In [7]:
# ####################################################################
def gauss_jordan(Ab: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de Gauss-Jordan.

    ## Parameters

    ``Ab``: matriz aumentada del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(n+1), donde n es el número de incógnitas.

    ## Return

    ``solucion``: vector con la solución del sistema de ecuaciones lineales.

    """
    if not isinstance(Ab, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        Ab = np.array(Ab, dtype=float)
    assert Ab.shape[0] == Ab.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = Ab.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if Ab[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(Ab[pi, i]) < abs(Ab[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = Ab[i, :].copy()
            Ab[i, :] = Ab[p, :].copy()
            Ab[p, :] = _aux

        # --- Eliminación: loop por fila
        for j in range(n):
            if i == j:
                continue
            m = Ab[j, i] / Ab[i, i]
            Ab[j, i:] = Ab[j, i:] - m * Ab[i, i:]

        logging.info(f"\n{Ab}")

    if Ab[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    # --- Sustitución hacia atrás
    solucion = np.zeros(n)

    for i in range(n - 1, -1, -1):
        solucion[i] = Ab[i, -1] / Ab[i, i]

    return solucion

In [8]:
%autoreload 2
from src import matriz_aumentada

A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
b = [1, -2, 3, 4]

Ab = matriz_aumentada(A, b)
gauss_jordan(Ab)

[08-17 22:21:19][INFO] 2025-08-17 22:21:19.436119
[08-17 22:21:19][INFO] DELL| 2025-08-17 22:21:19.445361
[08-17 22:21:19][INFO] 2025-08-17 22:21:19.453370
[08-17 22:21:19][INFO] DELL| 2025-08-17 22:21:19.459975
[08-17 22:21:19][INFO] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0. -1. -3. -6.  0.]]
[08-17 22:21:19][INFO] 
[[ 1.  0.  3.  6.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0. -3. -7. -4.]]
[08-17 22:21:19][INFO] 
[[ 1.  0.  0. -3.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0.  0.  2. -4.]]
[08-17 22:21:19][INFO] 
[[ 1.  0.  0.  0.  3.]
 [ 0.  1.  0.  0. -6.]
 [ 0.  0. -1.  0. -6.]
 [ 0.  0.  0.  2. -4.]]


array([ 3., -6.,  6., -2.])

# Resolver

In [9]:
# ####################################################################
import numpy as np  
def inv_matrix(A: np.ndarray) -> np.ndarray:
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)
        
    n = A.shape[0]
    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."
    
    # Creamos la matriz identidad del mismo tamaño que A
    I = np.identity(n)
    
    # Inicializamos la matriz inversa
    A_inv = np.zeros((n, n))
    
    # Para cada columna de la matriz identidad (que será el vector b)
    for i in range(n):
        # Resolvemos el sistema A * x = I[:,i] usando Gauss-Jordan
        Ab = matriz_aumentada(A, I[:, i])
        try:
            x = gauss_jordan(Ab)
            A_inv[:, i] = x
        except ValueError as e:
            raise ValueError("La matriz es singular (no invertible).") from e
    
    return A_inv

## Ejemplos
* Ejemplo 1

In [16]:
# La matriz A =
A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
# tiene como inversa
# A_inv =[[ 0.5, -0.5, -1.5,  1.5],
#        [-0.5,  1.5, -1.5,  0.5],
#        [-1.5, -1.5,  3.5, -1.5],
#        [ 1.5,  0.5, -1.5,  0.5]]
inv_matrix(A)



[08-17 22:22:08][INFO] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -2.]
 [ 0.  0. -1. -3. -3.]
 [ 0. -1. -3. -6. -4.]]
[08-17 22:22:08][INFO] 
[[ 1.  0.  3.  6.  5.]
 [ 0.  1.  0. -1. -2.]
 [ 0.  0. -1. -3. -3.]
 [ 0.  0. -3. -7. -6.]]
[08-17 22:22:08][INFO] 
[[ 1.  0.  0. -3. -4.]
 [ 0.  1.  0. -1. -2.]
 [ 0.  0. -1. -3. -3.]
 [ 0.  0.  0.  2.  3.]]
[08-17 22:22:08][INFO] 
[[ 1.   0.   0.   0.   0.5]
 [ 0.   1.   0.   0.  -0.5]
 [ 0.   0.  -1.   0.   1.5]
 [ 0.   0.   0.   2.   3. ]]
[08-17 22:22:08][INFO] 
[[ 1.  2.  3.  4.  0.]
 [ 0.  1.  0. -1.  1.]
 [ 0.  0. -1. -3.  0.]
 [ 0. -1. -3. -6.  0.]]
[08-17 22:22:08][INFO] 
[[ 1.  0.  3.  6. -2.]
 [ 0.  1.  0. -1.  1.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0. -3. -7.  1.]]
[08-17 22:22:08][INFO] 
[[ 1.  0.  0. -3. -2.]
 [ 0.  1.  0. -1.  1.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0.  0.  2.  1.]]
[08-17 22:22:08][INFO] 
[[ 1.   0.   0.   0.  -0.5]
 [ 0.   1.   0.   0.   1.5]
 [ 0.   0.  -1.   0.   1.5]
 [ 0.   0.   0.   2.   1. ]]
[08-17 22:22:08][INFO] 


array([[ 0.5, -0.5, -1.5,  1.5],
       [-0.5,  1.5, -1.5,  0.5],
       [-1.5, -1.5,  3.5, -1.5],
       [ 1.5,  0.5, -1.5,  0.5]])

* Ejemplo 2

In [17]:
# La matriz A =
A = [
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4],
]
# tiene como inversa
# A_inv =[[-34.,  31.,  52., -20.],
#         [ 19., -17., -29.,  11.],
#         [ 12., -11., -18.,   7.],
#         [  1.,  -1.,  -2.,   1.]]
inv_matrix(A)


[08-17 22:22:31][INFO] 
[[ 2.   1.   4.   1.   0. ]
 [ 0.   2.5 -4.   0.5  0. ]
 [ 0.   2.  -3.  -1.   1. ]
 [ 0.   0.5 -1.   2.5  0. ]]
[08-17 22:22:31][INFO] 
[[  2.    0.    6.   -4.    0. ]
 [  0.    0.5  -1.    2.5   0. ]
 [  0.    0.    1.  -11.    1. ]
 [  0.    0.    1.  -12.    0. ]]
[08-17 22:22:31][INFO] 
[[  2.    0.    0.   62.   -6. ]
 [  0.    0.5   0.   -8.5   1. ]
 [  0.    0.    1.  -11.    1. ]
 [  0.    0.    0.   -1.   -1. ]]


[08-17 22:22:31][INFO] 
[[  2.    0.    0.    0.  -68. ]
 [  0.    0.5   0.    0.    9.5]
 [  0.    0.    1.    0.   12. ]
 [  0.    0.    0.   -1.   -1. ]]
[08-17 22:22:31][INFO] 
[[ 2.   1.   4.   1.   0. ]
 [ 0.   2.5 -4.   0.5  1. ]
 [ 0.   2.  -3.  -1.   0. ]
 [ 0.   0.5 -1.   2.5  0. ]]
[08-17 22:22:31][INFO] 
[[  2.    0.    6.   -4.    0. ]
 [  0.    0.5  -1.    2.5   0. ]
 [  0.    0.    1.  -11.    0. ]
 [  0.    0.    1.  -12.    1. ]]
[08-17 22:22:31][INFO] 
[[  2.    0.    0.   62.    0. ]
 [  0.    0.5   0.   -8.5   0. ]
 [  0.    0.    1.  -11.    0. ]
 [  0.    0.    0.   -1.    1. ]]
[08-17 22:22:31][INFO] 
[[  2.    0.    0.    0.   62. ]
 [  0.    0.5   0.    0.   -8.5]
 [  0.    0.    1.    0.  -11. ]
 [  0.    0.    0.   -1.    1. ]]
[08-17 22:22:31][INFO] 
[[ 2.   1.   4.   1.   1. ]
 [ 0.   2.5 -4.   0.5 -1.5]
 [ 0.   2.  -3.  -1.  -2. ]
 [ 0.   0.5 -1.   2.5 -1.5]]
[08-17 22:22:31][INFO] 
[[  2.    0.    6.   -4.    4. ]
 [  0.    0.5  -1.    2.5  -1.5]
 [  0.  

array([[-34.,  31.,  52., -20.],
       [ 19., -17., -29.,  11.],
       [ 12., -11., -18.,   7.],
       [  1.,  -1.,  -2.,   1.]])

## Ejercicios

* Ejercicio 1

In [12]:
A = [[2, -3], [-1, 1]]
inv_matrix(A)

[08-17 22:21:20][INFO] 
[[-1.  1.  0.]
 [ 0. -1.  1.]]
[08-17 22:21:20][INFO] 
[[-1.  0.  1.]
 [ 0. -1.  1.]]
[08-17 22:21:20][INFO] 
[[-1.  1.  1.]
 [ 0. -1.  2.]]
[08-17 22:21:20][INFO] 
[[-1.  0.  3.]
 [ 0. -1.  2.]]


array([[-1., -3.],
       [-1., -2.]])

* Ejercicio 2

In [13]:
A = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
inv_matrix(A)

[08-17 22:21:20][INFO] 
[[  1.   0.   4.   0.   0.]
 [  0.   0. -16.   5.   1.]
 [  0.   4. -11.   3.   0.]
 [  0.   3.  -1.   0.   0.]]
[08-17 22:21:20][INFO] 
[[  1.           0.           4.           0.           0.        ]
 [  0.           3.          -1.           0.           0.        ]
 [  0.           0.          -9.66666667   3.           0.        ]
 [  0.           0.         -16.           5.           1.        ]]
[08-17 22:21:20][INFO] 
[[ 1.          0.          0.          1.24137931  0.        ]
 [ 0.          3.          0.         -0.31034483  0.        ]
 [ 0.          0.         -9.66666667  3.          0.        ]
 [ 0.          0.          0.          0.03448276  1.        ]]
[08-17 22:21:20][INFO] 
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -3.60000000e+01]
 [ 0.00000000e+00  3.00000000e+00  0.00000000e+00  0.00000000e+00
   9.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -9.66666667e+00  0.00000000e+00
  -8.70000000e+01]
 [ 0.00000

array([[-36.,  45.,  60., -80.],
       [  3.,  -4.,  -5.,   7.],
       [  9., -11., -15.,  20.],
       [ 29., -36., -48.,  64.]])

* Ejercicio 3

In [14]:
A = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0],
]
inv_matrix(A)

[08-17 22:21:20][INFO] 
[[-1. -1.  0.  0.  2.  1.  0.  0.  0.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  1.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.  0.]
 [ 0.  2.  1.  0. -3. -2.  0.  2.  0.]
 [ 0.  1.  0.  0. -1. -1.  0.  0.  0.]
 [ 0. -2. -1.  1.  4.  2.  0.  2.  0.]
 [ 0. -2.  0.  0.  4.  3.  2.  0.  0.]]
[08-17 22:21:20][INFO] 
[[-1.  0. -1.  1.  2.  0.  0.  1.  0.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  1.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.  0.]
 [ 0.  0.  3. -2. -3.  0.  0.  0.  0.]
 [ 0.  0.  1. -1. -1.  0.  0. -1.  0.]
 [ 0.  0. -3.  3.  4.  0.  0.  4.  0.]
 [ 0.  0. -2.  2.  4.  1.  2.  2.  0.]]
[08-17 22:21:20][INFO] 
[[-1.  0.  0.  0.  2.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  1.]
 [ 0.  0.  0.  1. -3. -3.  0.  3.  0.]
 [ 0.  0.  0.  0. -1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  4.  3.  0.  1.  0.]
 [ 0.  0.  0.  0.  4.  3.  2.

array([[ 2., -1., -0., -1., -0.,  2.,  2., -1.],
       [ 0.,  1.,  1., -1.,  0.,  0.,  0.,  0.],
       [ 6., -1., -0., -3.,  1.,  1.,  4., -3.],
       [ 6.,  1., -1., -3.,  1., -3.,  3., -3.],
       [ 2., -1.,  1., -1., -0.,  3.,  2., -1.],
       [-2.,  2., -0., -0., -0., -4., -2.,  1.],
       [-1.,  0.,  0.,  1.,  0.,  0., -1.,  1.],
       [-2.,  0.,  0.,  1.,  0.,  0., -1.,  1.]])

* Ejercicio 4

In [15]:
A = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
inv_matrix(A)

[08-17 22:21:20][INFO] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.  1.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0. -1.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.  1.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  1. -2.  1.]
 [ 0.  0.  0.  1.  0. -1. -1.  2. -2.  1. -1.]
 [ 0.  1.  1.  0.  2.  0. -1.  0. -2.  2. -1.]
 [ 0.  1.  1.  1.  1.  0.  1.  2. -1.  1. -1.]
 [ 0.  1.  1.  1.  2.  0. -1.  0. -1.  1. -1.]
 [ 0.  0. -1. -1. -1.  0.  1.  1.  1. -1.  0.]]
[08-17 22:21:20][INFO] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.  1.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0. -1.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.  1.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  1. -2.  1.]
 [ 0.  0.  0.  1.  0. -1. -1.  2. -2.  1. -1.]
 [ 0.  0.  1.  1.  2. -1. -1. -1. -2.  2.  0.]
 [ 0.  0.  1.  2.  1. -1.  1.  1. -1.  1.  0.]
 [ 0.  0.  1.  2.  2. -1. -1. -1. -1.  1.  0.]
 [ 0.  0. -1. -1. -1.  0.  1.  1.  1. -1.  0.]]
[08-17 22:

array([[ 14.,  -8.,   9.,  -4.,   0.,  -4.,   9.,   7.,  -8.,   3.],
       [ -2.,   2.,  -1.,   2.,   1.,   1.,  -1.,  -1.,   1.,  -2.],
       [-27.,  14., -18.,   5.,  -2.,   7., -17., -13.,  16.,  -2.],
       [ 12.,  -6.,   8.,  -2.,   1.,  -3.,   7.,   6.,  -7.,  -0.],
       [  6.,  -4.,   4.,  -2.,   0.,  -2.,   4.,   3.,  -3.,   2.],
       [ 18.,  -9.,  12.,  -4.,   1.,  -5.,  11.,   9., -11.,   1.],
       [  8.,  -4.,   5.,  -1.,   1.,  -2.,   5.,   4.,  -5.,  -0.],
       [ -5.,   2.,  -3.,   0.,  -1.,   1.,  -3.,  -2.,   3.,   1.],
       [-11.,   5.,  -7.,   1.,  -2.,   2.,  -7.,  -5.,   7.,   1.],
       [  1.,  -1.,   1.,  -1.,  -1.,  -1.,   1.,   1.,  -1.,   1.]])